#pragma once
#include <cstdint>

namespace ME
{
using RHIFlags = uint32_t;

enum ERHIMemoryPropertyFlagBits : RHIFlags
{
    RHI_MEMORY_PROPERTY_DEVICE_LOCAL_BIT = 0x00000001,
    RHI_MEMORY_PROPERTY_HOST_VISIBLE_BIT = 0x00000002,
    RHI_MEMORY_PROPERTY_HOST_COHERENT_BIT = 0x00000004,
    RHI_MEMORY_PROPERTY_HOST_CACHED_BIT = 0x00000008,
    RHI_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT = 0x00000010,
    RHI_MEMORY_PROPERTY_PROTECTED_BIT = 0x00000020,
    RHI_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD = 0x00000040,
    RHI_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD = 0x00000080,
    RHI_MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV = 0x00000100,
};

using RHIMemoryPropertyFlags = RHIFlags;

enum ERHITextureUsageFlagsBits : RHIFlags
{
    RHI_TEXTURE_USAGE_TRANSFER_SRC_BIT = 0x00000001,
    RHI_TEXTURE_USAGE_TRANSFER_DST_BIT = 0x00000002,
    RHI_TEXTURE_USAGE_SAMPLED_BIT = 0x00000004,
    RHI_TEXTURE_USAGE_STORAGE_BIT = 0x00000008,
    RHI_TEXTURE_USAGE_COLOR_ATTACHMENT_BIT = 0x00000010,
    RHI_TEXTURE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
    RHI_TEXTURE_USAGE_TRANSIENT_ATTACHMENT_BIT = 0x00000040,
    RHI_TEXTURE_USAGE_INPUT_ATTACHMENT_BIT = 0x00000080,
    RHI_TEXTURE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT = 0x00000200,
    RHI_TEXTURE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 0x00000100,
    RHI_TEXTURE_USAGE_INVOCATION_MASK_BIT_HUAWEI = 0x00040000,
    RHI_TEXTURE_USAGE_SHADING_RATE_IMAGE_BIT_NV = RHI_TEXTURE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,
};

using RHITextureUsageFlags = RHIFlags;

enum ERHIShaderStageFlagBits : RHIFlags
{
    RHI_SHADER_STAGE_VERTEX_BIT = 0x00000001,
    RHI_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 0x00000002,
    RHI_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 0x00000004,
    RHI_SHADER_STAGE_GEOMETRY_BIT = 0x00000008,
    RHI_SHADER_STAGE_FRAGMENT_BIT = 0x00000010,
    RHI_SHADER_STAGE_COMPUTE_BIT = 0x00000020,
    RHI_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
    RHI_SHADER_STAGE_ALL = 0x7FFFFFFF,
    RHI_SHADER_STAGE_RAYGEN_BIT_KHR = 0x00000100,
    RHI_SHADER_STAGE_ANY_HIT_BIT_KHR = 0x00000200,
    RHI_SHADER_STAGE_CLOSEST_HIT_BIT_KHR = 0x00000400,
    RHI_SHADER_STAGE_MISS_BIT_KHR = 0x00000800,
    RHI_SHADER_STAGE_INTERSECTION_BIT_KHR = 0x00001000,
    RHI_SHADER_STAGE_CALLABLE_BIT_KHR = 0x00002000,
    RHI_SHADER_STAGE_TASK_BIT_NV = 0x00000040,
    RHI_SHADER_STAGE_MESH_BIT_NV = 0x00000080,
    RHI_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI = 0x00004000,
    RHI_SHADER_STAGE_RAYGEN_BIT_NV = RHI_SHADER_STAGE_RAYGEN_BIT_KHR,
    RHI_SHADER_STAGE_ANY_HIT_BIT_NV = RHI_SHADER_STAGE_ANY_HIT_BIT_KHR,
    RHI_SHADER_STAGE_CLOSEST_HIT_BIT_NV = RHI_SHADER_STAGE_CLOSEST_HIT_BIT_KHR,
    RHI_SHADER_STAGE_MISS_BIT_NV = RHI_SHADER_STAGE_MISS_BIT_KHR,
    RHI_SHADER_STAGE_INTERSECTION_BIT_NV = RHI_SHADER_STAGE_INTERSECTION_BIT_KHR,
    RHI_SHADER_STAGE_CALLABLE_BIT_NV = RHI_SHADER_STAGE_CALLABLE_BIT_KHR,
};

using RHIShaderStageFlags = RHIFlags;

enum ERHIBufferUsageFlagBits : RHIFlags
{
    RHI_BUFFER_USAGE_TRANSFER_SRC_BIT = 0x00000001,
    RHI_BUFFER_USAGE_TRANSFER_DST_BIT = 0x00000002,
    RHI_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT = 0x00000004,
    RHI_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT = 0x00000008,
    RHI_BUFFER_USAGE_UNIFORM_BUFFER_BIT = 0x00000010,
    RHI_BUFFER_USAGE_STORAGE_BUFFER_BIT = 0x00000020,
    RHI_BUFFER_USAGE_INDEX_BUFFER_BIT = 0x00000040,
    RHI_BUFFER_USAGE_VERTEX_BUFFER_BIT = 0x00000080,
    RHI_BUFFER_USAGE_INDIRECT_BUFFER_BIT = 0x00000100,
    RHI_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT = 0x00020000,
    RHI_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT = 0x00000800,
    RHI_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT = 0x00001000,
    RHI_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT = 0x00000200,
    RHI_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR = 0x00080000,
    RHI_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR = 0x00100000,
    RHI_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR = 0x00000400,
    RHI_BUFFER_USAGE_RAY_TRACING_BIT_NV = RHI_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR,
    RHI_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT = RHI_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,
    RHI_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_KHR = RHI_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,
};

using RHIBufferUsageFlags = RHIFlags;

enum RHIAccessFlagBits : RHIFlags
{
    RHI_ACCESS_INDIRECT_COMMAND_READ_BIT = 0x00000001,
    RHI_ACCESS_INDEX_READ_BIT = 0x00000002,
    RHI_ACCESS_VERTEX_ATTRIBUTE_READ_BIT = 0x00000004,
    RHI_ACCESS_UNIFORM_READ_BIT = 0x00000008,
    RHI_ACCESS_INPUT_ATTACHMENT_READ_BIT = 0x00000010,
    RHI_ACCESS_SHADER_READ_BIT = 0x00000020,
    RHI_ACCESS_SHADER_WRITE_BIT = 0x00000040,
    RHI_ACCESS_COLOR_ATTACHMENT_READ_BIT = 0x00000080,
    RHI_ACCESS_COLOR_ATTACHMENT_WRITE_BIT = 0x00000100,
    RHI_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT = 0x00000200,
    RHI_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT = 0x00000400,
    RHI_ACCESS_TRANSFER_READ_BIT = 0x00000800,
    RHI_ACCESS_TRANSFER_WRITE_BIT = 0x00001000,
    RHI_ACCESS_HOST_READ_BIT = 0x00002000,
    RHI_ACCESS_HOST_WRITE_BIT = 0x00004000,
    RHI_ACCESS_MEMORY_READ_BIT = 0x00008000,
    RHI_ACCESS_MEMORY_WRITE_BIT = 0x00010000,
    RHI_ACCESS_NONE = 0,
    RHI_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT = 0x02000000,
    RHI_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT = 0x04000000,
    RHI_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT = 0x08000000,
    RHI_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT = 0x00100000,
    RHI_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT = 0x00080000,
    RHI_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR = 0x00200000,
    RHI_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR = 0x00400000,
    RHI_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT = 0x01000000,
    RHI_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR = 0x00800000,
    RHI_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV = 0x00020000,
    RHI_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV = 0x00040000,
    RHI_ACCESS_SHADING_RATE_IMAGE_READ_BIT_NV = RHI_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR,
    RHI_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV = RHI_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR,
    RHI_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_NV = RHI_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR,
    RHI_ACCESS_NONE_KHR = RHI_ACCESS_NONE,
    RHI_ACCESS_COMMAND_PREPROCESS_READ_BIT_EXT = RHI_ACCESS_COMMAND_PREPROCESS_READ_BIT_NV,
    RHI_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_EXT = RHI_ACCESS_COMMAND_PREPROCESS_WRITE_BIT_NV,
};

using RHIAccessFlags = RHIFlags;

enum ERHIPipelineStageFlagBits : RHIFlags
{
    RHI_PIPELINE_STAGE_TOP_OF_PIPE_BIT = 0x00000001,
    RHI_PIPELINE_STAGE_DRAW_INDIRECT_BIT = 0x00000002,
    RHI_PIPELINE_STAGE_VERTEX_INPUT_BIT = 0x00000004,
    RHI_PIPELINE_STAGE_VERTEX_SHADER_BIT = 0x00000008,
    RHI_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT = 0x00000010,
    RHI_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT = 0x00000020,
    RHI_PIPELINE_STAGE_GEOMETRY_SHADER_BIT = 0x00000040,
    RHI_PIPELINE_STAGE_FRAGMENT_SHADER_BIT = 0x00000080,
    RHI_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT = 0x00000100,
    RHI_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT = 0x00000200,
    RHI_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT = 0x00000400,
    RHI_PIPELINE_STAGE_COMPUTE_SHADER_BIT = 0x00000800,
    RHI_PIPELINE_STAGE_TRANSFER_BIT = 0x00001000,
    RHI_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT = 0x00002000,
    RHI_PIPELINE_STAGE_HOST_BIT = 0x00004000,
    RHI_PIPELINE_STAGE_ALL_GRAPHICS_BIT = 0x00008000,
    RHI_PIPELINE_STAGE_ALL_COMMANDS_BIT = 0x00010000,
    RHI_PIPELINE_STAGE_NONE = 0,
    RHI_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT = 0x01000000,
    RHI_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT = 0x00040000,
    RHI_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR = 0x02000000,
    RHI_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR = 0x00200000,
    RHI_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT = 0x00800000,
    RHI_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR = 0x00400000,
    RHI_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV = 0x00020000,
    RHI_PIPELINE_STAGE_TASK_SHADER_BIT_EXT = 0x00080000,
    RHI_PIPELINE_STAGE_MESH_SHADER_BIT_EXT = 0x00100000,
    RHI_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV = RHI_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,
    RHI_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV = RHI_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,
    RHI_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV = RHI_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
    RHI_PIPELINE_STAGE_TASK_SHADER_BIT_NV = RHI_PIPELINE_STAGE_TASK_SHADER_BIT_EXT,
    RHI_PIPELINE_STAGE_MESH_SHADER_BIT_NV = RHI_PIPELINE_STAGE_MESH_SHADER_BIT_EXT,
    RHI_PIPELINE_STAGE_NONE_KHR = RHI_PIPELINE_STAGE_NONE,
    RHI_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_EXT = RHI_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV,
};

using RHIPipelineStageFlags = RHIFlags;

enum RHIImageAspectFlagBits : RHIFlags
{
    RHI_IMAGE_ASPECT_COLOR_BIT = 0x00000001,
    RHI_IMAGE_ASPECT_DEPTH_BIT = 0x00000002,
    RHI_IMAGE_ASPECT_STENCIL_BIT = 0x00000004,
    RHI_IMAGE_ASPECT_METADATA_BIT = 0x00000008,
    RHI_IMAGE_ASPECT_PLANE_0_BIT = 0x00000010,
    RHI_IMAGE_ASPECT_PLANE_1_BIT = 0x00000020,
    RHI_IMAGE_ASPECT_PLANE_2_BIT = 0x00000040,
    RHI_IMAGE_ASPECT_NONE = 0,
    RHI_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT = 0x00000080,
    RHI_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT = 0x00000100,
    RHI_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT = 0x00000200,
    RHI_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT = 0x00000400,
    RHI_IMAGE_ASPECT_PLANE_0_BIT_KHR = RHI_IMAGE_ASPECT_PLANE_0_BIT,
    RHI_IMAGE_ASPECT_PLANE_1_BIT_KHR = RHI_IMAGE_ASPECT_PLANE_1_BIT,
    RHI_IMAGE_ASPECT_PLANE_2_BIT_KHR = RHI_IMAGE_ASPECT_PLANE_2_BIT,
    RHI_IMAGE_ASPECT_NONE_KHR = RHI_IMAGE_ASPECT_NONE,
};

using RHIImageAspectFlags = RHIFlags;

enum class ERHIImageLayout
{
    RHI_IMAGE_LAYOUT_UNDEFINED,
    RHI_IMAGE_LAYOUT_GENERAL,
    RHI_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
    RHI_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
    RHI_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
    RHI_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
    RHI_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
    RHI_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
    RHI_IMAGE_LAYOUT_PREINITIALIZED,
    RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
    RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
    RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
    RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
    RHI_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
    RHI_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
    RHI_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
    RHI_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
    RHI_IMAGE_LAYOUT_PRESENT_SRC_KHR,
    RHI_IMAGE_LAYOUT_SHARED_PRESENT_KHR,
    RHI_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
    RHI_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV,
    RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR,
    RHI_IMAGE_LAYOUT_MAX_ENUM
};

enum class ERHIDescriptorType : uint32_t
{
    RHI_DESCRIPTOR_TYPE_SAMPLER,
    RHI_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
    RHI_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
    RHI_DESCRIPTOR_TYPE_STORAGE_IMAGE,
    RHI_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
    RHI_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
    RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
    RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER,
    RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
    RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
    RHI_DESCRIPTOR_TYPE_INPUT_ATTACHMENT,
    RHI_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK,
    RHI_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR,
    RHI_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV,
    RHI_DESCRIPTOR_TYPE_MUTABLE_VALVE,
    RHI_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT,
    RHI_DESCRIPTOR_TYPE_MAX_ENUM
};

}  //namespace ME