set(TARGET_NAME Third_glm)

set(GLM_PORJ_DIR ${PROJ_THIRDPARTY_DIR}/glm)
set(GLM_SRC_DIR ${GLM_PORJ_DIR}/glm)

file(GLOB GLM_ROOT_SOURCE ${GLM_SRC_DIR}/*.cpp)
file(GLOB GLM_ROOT_INLINE ${GLM_SRC_DIR}/*.inl)
file(GLOB GLM_ROOT_HEADER ${GLM_SRC_DIR}/*.hpp)
file(GLOB GLM_ROOT_TEXT ${GLM_SRC_DIR}/../*.txt)
file(GLOB GLM_ROOT_MD ${GLM_SRC_DIR}/../*.md)
file(GLOB GLM_ROOT_NAT ${GLM_SRC_DIR}/../util/glm.natvis)
file(GLOB_RECURSE GLM_CORE_SOURCE ${GLM_SRC_DIR}/./detail/*.cpp)
file(GLOB_RECURSE GLM_CORE_INLINE ${GLM_SRC_DIR}/./detail/*.inl)
file(GLOB_RECURSE GLM_CORE_HEADER ${GLM_SRC_DIR}/./detail/*.hpp)
file(GLOB_RECURSE GLM_EXT_SOURCE ${GLM_SRC_DIR}/./ext/*.cpp)
file(GLOB_RECURSE GLM_EXT_INLINE ${GLM_SRC_DIR}/./ext/*.inl)
file(GLOB_RECURSE GLM_EXT_HEADER ${GLM_SRC_DIR}/./ext/*.hpp)
file(GLOB_RECURSE GLM_GTC_SOURCE ${GLM_SRC_DIR}/./gtc/*.cpp)
file(GLOB_RECURSE GLM_GTC_INLINE ${GLM_SRC_DIR}/./gtc/*.inl)
file(GLOB_RECURSE GLM_GTC_HEADER ${GLM_SRC_DIR}/./gtc/*.hpp)
file(GLOB_RECURSE GLM_GTX_SOURCE ${GLM_SRC_DIR}/./gtx/*.cpp)
file(GLOB_RECURSE GLM_GTX_INLINE ${GLM_SRC_DIR}/./gtx/*.inl)
file(GLOB_RECURSE GLM_GTX_HEADER ${GLM_SRC_DIR}/./gtx/*.hpp)
file(GLOB_RECURSE GLM_SIMD_SOURCE ${GLM_SRC_DIR}/./simd/*.cpp)
file(GLOB_RECURSE GLM_SIMD_INLINE ${GLM_SRC_DIR}/./simd/*.inl)
file(GLOB_RECURSE GLM_SIMD_HEADER ${GLM_SRC_DIR}/./simd/*.h)

set(GLM_SOURCES
    ${GLM_ROOT_TEXT}   ${GLM_ROOT_MD}     ${GLM_ROOT_NAT}
    ${GLM_ROOT_SOURCE} ${GLM_ROOT_INLINE} ${GLM_ROOT_HEADER}
    ${GLM_CORE_SOURCE} ${GLM_CORE_INLINE} ${GLM_CORE_HEADER}
    ${GLM_EXT_SOURCE}  ${GLM_EXT_INLINE}  ${GLM_EXT_HEADER}
    ${GLM_GTC_SOURCE}  ${GLM_GTC_INLINE}  ${GLM_GTC_HEADER}
    ${GLM_GTX_SOURCE}  ${GLM_GTX_INLINE}  ${GLM_GTX_HEADER}
    ${GLM_SIMD_SOURCE} ${GLM_SIMD_INLINE} ${GLM_SIMD_HEADER}
)

add_library(${TARGET_NAME} STATIC ${GLM_SOURCES})
target_include_directories(${TARGET_NAME} PUBLIC ${GLM_PORJ_DIR})
set_target_properties(${TARGET_NAME} PROPERTIES FOLDER Source/ThirdParty)
source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${GLM_SOURCES})