#include "MechanicEngine/Include/Event/EventUtils.h"

namespace ME
{
namespace Util
{
const char* KeyCodeInStr(KeyCode keycode)
{
    switch (keycode)
    {
        case KeyCode::Unknow:
            return "Unknow";
        case KeyCode::Space:
            return "Space";
        case KeyCode::Apostrophe:
            return "Apostrophe";
        case KeyCode::Comma:
            return "Comma";
        case KeyCode::Minus:
            return "Minus";
        case KeyCode::Period:
            return "Period";
        case KeyCode::Slash:
            return "Slash";
        case KeyCode::D0:
            return "D0";
        case KeyCode::D1:
            return "D1";
        case KeyCode::D2:
            return "D2";
        case KeyCode::D3:
            return "D3";
        case KeyCode::D4:
            return "D4";
        case KeyCode::D5:
            return "D5";
        case KeyCode::D6:
            return "D6";
        case KeyCode::D7:
            return "D7";
        case KeyCode::D8:
            return "D8";
        case KeyCode::D9:
            return "D9";
        case KeyCode::Semicolon:
            return "Semicolon";
        case KeyCode::Equal:
            return "Equal";
        case KeyCode::A:
            return "A";
        case KeyCode::B:
            return "B";
        case KeyCode::C:
            return "C";
        case KeyCode::D:
            return "D";
        case KeyCode::E:
            return "E";
        case KeyCode::F:
            return "F";
        case KeyCode::G:
            return "G";
        case KeyCode::H:
            return "H";
        case KeyCode::I:
            return "I";
        case KeyCode::J:
            return "J";
        case KeyCode::K:
            return "K";
        case KeyCode::L:
            return "L";
        case KeyCode::M:
            return "M";
        case KeyCode::N:
            return "N";
        case KeyCode::O:
            return "O";
        case KeyCode::P:
            return "P";
        case KeyCode::Q:
            return "Q";
        case KeyCode::R:
            return "R";
        case KeyCode::S:
            return "S";
        case KeyCode::T:
            return "T";
        case KeyCode::U:
            return "U";
        case KeyCode::V:
            return "V";
        case KeyCode::W:
            return "W";
        case KeyCode::X:
            return "X";
        case KeyCode::Y:
            return "Y";
        case KeyCode::Z:
            return "Z";
        case KeyCode::LeftBracket:
            return "LeftBracket";
        case KeyCode::Backslash:
            return "Backslash";
        case KeyCode::RightBracket:
            return "RightBracket";
        case KeyCode::GraveAccent:
            return "GraveAccent";
        case KeyCode::World1:
            return "World1";
        case KeyCode::World2:
            return "World2";
        case KeyCode::Escape:
            return "Escape";
        case KeyCode::Enter:
            return "Enter";
        case KeyCode::Tab:
            return "Tab";
        case KeyCode::Backspace:
            return "Backspace";
        case KeyCode::Insert:
            return "Insert";
        case KeyCode::Delete:
            return "Delete";
        case KeyCode::Right:
            return "Right";
        case KeyCode::Left:
            return "Left";
        case KeyCode::Down:
            return "Down";
        case KeyCode::Up:
            return "Up";
        case KeyCode::PageUp:
            return "PageUp";
        case KeyCode::PageDown:
            return "PageDown";
        case KeyCode::Home:
            return "Home";
        case KeyCode::End:
            return "End";
        case KeyCode::CapsLock:
            return "CapsLock";
        case KeyCode::ScrollLock:
            return "ScrollLock";
        case KeyCode::NumLock:
            return "NumLock";
        case KeyCode::PrintScreen:
            return "PrintScreen";
        case KeyCode::Pause:
            return "Pause";
        case KeyCode::F1:
            return "F1";
        case KeyCode::F2:
            return "F2";
        case KeyCode::F3:
            return "F3";
        case KeyCode::F4:
            return "F4";
        case KeyCode::F5:
            return "F5";
        case KeyCode::F6:
            return "F6";
        case KeyCode::F7:
            return "F7";
        case KeyCode::F8:
            return "F8";
        case KeyCode::F9:
            return "F9";
        case KeyCode::F10:
            return "F10";
        case KeyCode::F11:
            return "F11";
        case KeyCode::F12:
            return "F12";
        case KeyCode::F13:
            return "F13";
        case KeyCode::F14:
            return "F14";
        case KeyCode::F15:
            return "F15";
        case KeyCode::F16:
            return "F16";
        case KeyCode::F17:
            return "F17";
        case KeyCode::F18:
            return "F18";
        case KeyCode::F19:
            return "F19";
        case KeyCode::F20:
            return "F20";
        case KeyCode::F21:
            return "F21";
        case KeyCode::F22:
            return "F22";
        case KeyCode::F23:
            return "F23";
        case KeyCode::F24:
            return "F24";
        case KeyCode::F25:
            return "F25";
        case KeyCode::KP0:
            return "KP0";
        case KeyCode::KP1:
            return "KP1";
        case KeyCode::KP2:
            return "KP2";
        case KeyCode::KP3:
            return "KP3";
        case KeyCode::KP4:
            return "KP4";
        case KeyCode::KP5:
            return "KP5";
        case KeyCode::KP6:
            return "KP6";
        case KeyCode::KP7:
            return "KP7";
        case KeyCode::KP8:
            return "KP8";
        case KeyCode::KP9:
            return "KP9";
        case KeyCode::KPDecimal:
            return "KPDecimal";
        case KeyCode::KPDivide:
            return "KPDivide";
        case KeyCode::KPMultiply:
            return "KPMultiply";
        case KeyCode::KPSubtract:
            return "KPSubtract";
        case KeyCode::KPAdd:
            return "KPAdd";
        case KeyCode::KPEnter:
            return "KPEnter";
        case KeyCode::KPEqual:
            return "KPEqual";
        case KeyCode::LeftShift:
            return "LeftShift";
        case KeyCode::LeftControl:
            return "LeftControl";
        case KeyCode::LeftAlt:
            return "LeftAlt";
        case KeyCode::LeftSuper:
            return "LeftSuper";
        case KeyCode::RightShift:
            return "RightShift";
        case KeyCode::RightControl:
            return "RightControl";
        case KeyCode::RightAlt:
            return "RightAlt";
        case KeyCode::RightSuper:
            return "RightSuper";
        case KeyCode::Menu:
            return "Menu";
        default:
            return "Unknow";
    }
}

const char* MouseCodeInStr(MouseCode mouseCode)
{
    switch (mouseCode)
    {
        case MouseCode::Unkown:
            return "Unknown";
        case MouseCode::Button0:
            return "Button0";
        case MouseCode::Button1:
            return "Button1";
        case MouseCode::Button2:
            return "Button2";
        case MouseCode::Button3:
            return "Button3";
        case MouseCode::Button4:
            return "Button4";
        case MouseCode::Button5:
            return "Button5";
        case MouseCode::Button6:
            return "Button6";
        case MouseCode::Button7:
            return "Button7";
        default:
            return "Unknown";
    }
}
}  //namespace Util

}  //namespace ME
